version: '2'
services:
  llama2-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data:delegated
    ports:
      - "8000:8000"
    platform: linux/amd64
  ui:
    build:
      context: .
      dockerfile: ui.Dockerfile
    ports:
      - "3000:3000"